services:
  service-desk-server:
    build: .
    restart: always
    depends_on:
      - mysql
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - wb-nest-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBNAME}
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    env_file: .env
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${DBPASS}

volumes:
  wb-nest-data:
