-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 20:27:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET
    @OLD_UNIQUE_CHECKS = @ @UNIQUE_CHECKS,
    UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @ @SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wb-nest-data
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wb-nest-data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wb-nest-data` DEFAULT CHARACTER SET utf8;

USE `wb-nest-data`;

-- -----------------------------------------------------
-- Table `wb-nest-data`.`ProductCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wb-nest-data`.`ProductCard` (
    `imtId` INT NOT NULL AUTO_INCREMENT,
    `object` VARCHAR(45) NULL,
    `nmId` INT NULL,
    `vendorCode` VARCHAR(45) NULL,
    `isProhibitet` TINYINT(1) NOT NULL DEFAULT 0,
    `createdAt` DATETIME NULL,
    `updatedAt` DATETIME NULL,
    PRIMARY KEY (`imtId`),
    UNIQUE INDEX `vendorCode_UNIQUE` (`vendorCode` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wb-nest-data`.`MediaFile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wb-nest-data`.`MediaFile` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `originalName` VARCHAR(45) NULL,
    `URL` VARCHAR(45) NULL,
    `createdAt` DATETIME NULL,
    `updatedAt` DATETIME NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wb-nest-data`.`ProductCardMediaFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wb-nest-data`.`ProductCardMediaFiles` (
    `productCardImtId` INT NOT NULL,
    `mediaFileId` INT NOT NULL,
    `createdAt` DATETIME NULL,
    `updatedAt` DATETIME NULL,
    PRIMARY KEY (`productCardImtId`, `mediaFileId`),
    INDEX `fk_ProductCard_has_MediaFile_MediaFile1_idx` (`mediaFileId` ASC),
    CONSTRAINT `fk_ProductCard_has_MediaFile_ProductCard` FOREIGN KEY (`productCardImtId`) REFERENCES `wb-nest-data`.`ProductCard` (`imtId`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_ProductCard_has_MediaFile_MediaFile1` FOREIGN KEY (`mediaFileId`) REFERENCES `wb-nest-data`.`MediaFile` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wb-nest-data`.`Characteristic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wb-nest-data`.`Characteristic` (
    `id` INT NOT NULL,
    `name` VARCHAR(45) NULL,
    `createdAt` DATETIME NULL,
    `updatedAt` DATETIME NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wb-nest-data`.`ProductCardCharacteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wb-nest-data`.`ProductCardCharacteristics` (
    `productCardImtId` INT NOT NULL,
    `characteristicId` INT NOT NULL,
    `createdAt` DATETIME NULL,
    `value` VARCHAR(45) NULL,
    `updatedAt` DATETIME NULL,
    PRIMARY KEY (`productCardImtId`, `characteristicId`),
    INDEX `fk_ProductCard_has_Charactersitic_Charactersitic1_idx` (`characteristicId` ASC),
    INDEX `fk_ProductCard_has_Charactersitic_ProductCard1_idx` (`productCardImtId` ASC),
    CONSTRAINT `fk_ProductCard_has_Charactersitic_ProductCard1` FOREIGN KEY (`productCardImtId`) REFERENCES `wb-nest-data`.`ProductCard` (`imtId`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_ProductCard_has_Charactersitic_Charactersitic1` FOREIGN KEY (`characteristicId`) REFERENCES `wb-nest-data`.`Characteristic` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

SET
    SQL_MODE = @OLD_SQL_MODE;

SET
    FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
    UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;